version: "3.5"

services:

  nginx:
    build: nginx
    image: movie_image_nginx
    volumes:
      - ../mounts/media:/media/
      - ../mounts/static:/static/
    ports:
      - 8000:8000
    depends_on:
      - backend
    container_name: movie_nginx
    restart: on-failure

  backend:
    build: app
    image: movie_image_backend
    volumes:
      - ../mounts/media:/app/media/
      - ../mounts/static:/app/static/
    container_name: movie_backend
    expose:
      - "8080"
    env_file:
      - .env.sample
    depends_on:
      - db
    restart: on-failure

  elasticsearch:
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - ../postgresql/data:/var/lib/postgresql/data
    env_file: .env.sample
    container_name: movie_db
    restart: on-failure
